SELECT * FROM [NhanesData].[dbo].[OHXPER]
	INNER JOIN dbo.SMQ
        ON SMQ.SEQN = OHXPER.SEQN
	INNER JOIN dbo.SMQFAM
        ON SMQFAM.SEQN = OHXPER.SEQN
	INNER JOIN dbo.SMQRTU
        ON SMQRTU.SEQN = OHXPER.SEQN
	INNER JOIN dbo.SMQSHS
        ON SMQSHS.SEQN = OHXPER.SEQN